INSERT INTO 
    faq (question, answer, category)
VALUES
    ('Who can access GAMECHANGER?','Anyone on NIPRnet with a Common Access Card (CAC) can access GAMECHANGER: https://gamechanger.advana.data.mil. If you have an Advana account, you can also access GAMECHANGER using a different link: https://search.advana.data.mil/#/gamechanger. Both these links provide the same GAMECHANGER experience.','general'),
    ('What browser should I use to access GAMECHANGER?','GAMECHANGER is optimized for use on Google Chrome.','general'),
    ('Is GAMECHANGER available on SIPR or JWICS?','GAMECHANGER is available on SIPR with an Advana account: https://advana.data.smil.mil/#/gamechanger. Note that not all features and functionality supported in our NIPR instance are available in SIPR just yet, but we are quickly making our SIPR instance more robust. Currently, GAMECHANGER is not available on JWICS, but we hope to deploy there in the future.','general'),
    ('Can I contribute to GAMECHANGER’s code base or leverage any existing code myself?', 'Yes! GAMECHANGER is fully open-sourced on GitHub under an MIT license: https://github.com/dod-advana/gamechanger. We welcome comments, suggestions, PRs, etc. Let us know if you’d like a walkthrough of our codebase.', 'general'),
    ('Help! Where do I go for extra assistance?','It’s easy to get in touch with the GAMECHANGER team. From within the GAMECHANGER application, simply submit a question/comment/suggestion through our User Feedback form, which is accessible via the left-hand side menu. Or feel free to email us @ osd.pentagon.ousd-c.mbx.advana-gamechanger@mail.mil.','general'),
    ('What is a GAMECHANGER clone?', 'GAMECHANGER technology is scalable and can be applied to use cases other than just policy. We refer to other “versions” of GAMECHANGER that are based on a different underlying corpus as clones. To date, we have 5 clones in production that are each focused on a specific use case. Our EDA clone, as an example, allows for search and discovery on DoD contract data. Clones can be customized and include features tailored to the particular use case.', 'clones'),
    ('How do I request a clone?', 'The first step would be to fill out our Clone Request form accessible via the left-hand side menu. The form requests information about your use case including use case background, data, expected users, permissions required, and any planned features. Once we receive your completed form, the GAMECHANGER Team will review your use case and initiate follow-up discussions as needed to determine feasibility and Level of Effort.', 'clones'),
    ('What is the Graph View and how do I use it?', 'Built on Neo4j, the Graph View visualizes complex relationships between documents by presenting nodes on a directed graph with edges. Each node represents a different document from the search results. Each edge represents a connection between documents. These connections are determined based upon references made within documents themselves. The Graph View is fully interactive and can be magnified to see more details. Clicking on a node provides a set of options to explore the document further, including an icon that opens the document card.','graph view'),
    ('How do I request additional data be added to the GAMECHANGER corpus?','Reach out to us directly – either via our User Feedback form or via email @ osd.pentagon.ousd-c.mbx.advana-gamechanger@mail.mil.','data'),
    ('Where do I go to find out what policy documents are currently in GAMECHANGER?','Check out our Data Status tracker, accessible via the left-hand side menu. The “Documents” tab includes a filterable table of every policy or requirement within the GAMECHANGER corpus. The “Progress” and “Updates” tabs provide insight into the crawler ingestion status of each source within the corpus.','data'),
    ('How frequently is the GAMECHANGER corpus updated?','Our automated crawlers typically run every 7 days. You can check the status of our crawlers at any time by navigating to the Data Status Tracker.','data'),
    ('What is the Responsibility Explorer and how do I use it?','The Responsibility Explorer extracts responsibilities stated within documents and assigns it to the entity responsible. Within the Responsibility Explorer, you can search for all responsibilities assigned to a particular entity (such as “Director, DIA”).','analyst tools'),
    ('How do I share search queries or results with a colleague?','After running a search, click the arrow icon in the upper right-hand corner of the screen and a unique link is automatically copied to your clipboard. Going to that link in your browser will run the same search, with any filters applied, and show the same results.','collaboration'),
    ('How do export my search results?','Click the export icon in the upper right-hand corner of the screen. You have the option to choose among PDF, JSON, or CSV formats. If you wish to only export a subset of results, first check the box on the top right corner of the document card and then click the export icon.','collaboration');
