INSERT INTO public.organization_info (org_name, org_acronym, image_link) VALUES
('Centers for Disease Control and Prevention','CDC','s3://advana-raw-zone/gamechanger/organization_images/cdc logo.svg'),
('National Archives and Records Administration', 'NARA', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_National_Archives_and_Records_Administration.svg'),
('United States Air Force', 'USAF', 's3://advana-raw-zone/gamechanger/organization_images/Mark_of_the_United_States_Air_Force.svg'),
('United States Army', 'USA', 's3://advana-raw-zone/gamechanger/organization_images/Mark_of_the_United_States_Army.svg'),
('United States Navy', 'USN', 's3://advana-raw-zone/gamechanger/organization_images/Mark_of_the_United_States_Navy.svg'),
('United States Marine Corps', 'USMC', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Marine_Corps.svg'),
('Occupational Safety and Health Administration', 'OSHA', 's3://advana-raw-zone/gamechanger/organization_images/OSHA_seal.jpg'),
('White House', 'none', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_President_of_the_United_States.svg'),
('Small Business Administration', 'SBA', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Small_Business_Administration.svg'),
('Office of Management and Budget', 'OMB', 's3://advana-raw-zone/gamechanger/organization_images/omb-seal.png'),
('Office of Science and Technology Policy', 'OSTP', 's3://advana-raw-zone/gamechanger/organization_images/US-OfficeOfScienceAndTechnologyPolicy-2003Seal.svg'),
('General Services Administration', 'GSA', 's3://advana-raw-zone/gamechanger/organization_images/US-GeneralServicesAdministration-Seal-Alt.svg'),
('National Institute of Standards and Technology', 'NIST', 's3://advana-raw-zone/gamechanger/organization_images/nist_logo.png'),
('Office of Personnel Management', 'OPM', 's3://advana-raw-zone/gamechanger/organization_images/opm-seal.png'),
('United States Coast Guard', 'USCG', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Coast_Guard.svg'),
('Chief Acquisition Officers Council', 'CAOC', 's3://advana-raw-zone/gamechanger/organization_images/Chief Acquisition Officers Council_logo.jpg'),
('Immigration and Customs Enforcement', 'ICE', 's3://advana-raw-zone/gamechanger/organization_images/Immigration and Customs Enforcement.png'),
('Office of Environmental Management', 'none', 'none'),
('Equal Employment Opportunity Commission', 'EEOC', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Equal_Employment_Opportunity_Commission.svg'),
('Marine Forces Command', 'MARFORCOM', 's3://advana-raw-zone/gamechanger/organization_images/MARFORCOM.png'),
('Federal Aviation Administration', 'FAA', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Federal_Aviation_Administration.svg'),
('Bureau of Labor Statistics', 'BLS', 's3://advana-raw-zone/gamechanger/organization_images/Bureau_of_Labor_Statistics_logo.svg'),
('Central Intelligence Agency', 'CIA', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_Central_Intelligence_Agency.svg'),
('National Science Foundation', 'NSF', 's3://advana-raw-zone/gamechanger/organization_images/NSF_logo.png'),
('Internal Revenue Service', 'IRS', 's3://advana-raw-zone/gamechanger/organization_images/Logo_of_the_Internal_Revenue_Service.svg'),
('Smithsonian Institution', 'none', 's3://advana-raw-zone/gamechanger/organization_images/Smithsonian_logo_color.svg'),
('Tennessee Valley Authority', 'TVA', 's3://advana-raw-zone/gamechanger/organization_images/US-TennesseeValleyAuthority-Logo.svg'),
('Federal Emergency Management Agency', 'FEMA', 's3://advana-raw-zone/gamechanger/organization_images/FEMA_logo.svg'),
('Supreme Court of the United States', 'SCOTUS', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Supreme_Court.svg'),
('United States Fire Administration', 'USFA', 's3://advana-raw-zone/gamechanger/organization_images/UnitedStatesFireAdministration-Logo.svg'),
('Bureau of Alcohol, Tobacco, Firearms and Explosives', 'ATF', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_Bureau_of_Alcohol_Tobacco_Firearms_and_Explosives.svg'),
('United States Department of Homeland Security', 'DHS', 's3://advana-raw-zone/gamechanger/organization_images/Seal_of_the_United_States_Department_of_Homeland_Security.svg'),
('United States Department of Defense', 'DOD', 's3://advana-raw-zone/gamechanger/organization_images/United_States_Department_of_Defense_Seal.svg');
