image: node:14 # "${IRONBANK_NODEJS}"

stages:          # List of stages for jobs, and their order of execution
  - security-test
  - lint
  - unit-test
  - integration-test
  - deploy

before_script:
  - npm set "@dod-advana:registry" "https://npm.pkg.github.com"
  - npm set "//npm.pkg.github.com/:_authToken" "${NPM_AUTH_TOKEN}"

sonar_scan-job:
  stage: security-test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  artifacts:
    paths:
      - "public"
  variables:
    REPOSITORY: "${CI_PROJECT_PATH}"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    SONAR_HOST_EXTERNAL_URL: "${SONAR_HOST_EXTERNAL_URL}"
    SONAR_HOST_URL: "${SONAR_HOST_URL}"
    SONAR_TOKEN: "${SONAR_TOKEN}"
    PROJECTURL: "${CI_REPOSITORY_URL}"
    PROJECTNAME: "${CI_PROJECT_PATH}"
    PROJECTKEY: "${CI_PROJECT_PATH_SLUG}"
    GITLAB_PROJECT_ID: "${CI_PROJECT_ID}"
    GITLAB_COMMIT_SHA: "${CI_COMMIT_SHA}"
    GITLAB_REF_NAME: "${CI_COMMIT_REF_NAME}"
    GITLAB_BRANCH_NAME: "${CI_COMMIT_BRANCH}"
    CODEQUALITY_REPORT_ARTIFACT: "sonarqube-report.html"
    GIT_DEPTH: "0"
  script:
    - |
      sonar-scanner \
        -Dsonar.qualitygate.wait=true \
        -Dsonar.projectName="${PROJECTNAME}" \
        -Dsonar.projectKey="${PROJECTKEY}" \
        -Dsonar.links.ci="${PROJECTURL}/pipelines" \
        -Dsonar.links.issue="${PROJECTURL}/issues" \
        -Dsonar.analysis.mode="publish" \
        -Dsonar.gitlab.project_id="${GITLAB_PROJECT_ID}" \
        -Dsonar.gitlab.commit_sha="${GITLAB_COMMIT_SHA}" \
        -Dsonar.gitlab.ref_name="${GITLAB_REF_NAME}"
      mkdir -p public
      <<-EOF cat > "public/${CODEQUALITY_REPORT_ARTIFACT}"
      <html>
      <head>
      <meta http-equiv="refresh" content="0; url=${SONAR_HOST_EXTERNAL_URL}/dashboard?id=${PROJECTKEY}" />
      </head>
      </html>
      EOF

lint-frontend-test-job:  
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key: 
      files:
        - frontend/package-lock.json
    paths:
    - .npm/
  script:
    - cd frontend && npm ci --cache ../.npm --prefer-offline
    - npx eslint --ext .js src

lint-backend-test-job:   
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key: 
      files:
        - backend/package-lock.json
    paths:
    - .npm/
  script:
    - cd backend && npm ci --cache ../.npm --prefer-offline
    - npx eslint --ext .js node_app

unit-backend-test-job:  
  stage: unit-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    key: 
      files:
        - backend/package-lock.json
    paths:
    - .npm/
  script:
    - cd backend && npm ci --cache ../.npm --prefer-offline
    - npm run test:gitlab
  artifacts:
    when: always
    reports:
      junit:
        - backend/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage/cobertura-coverage.xml

integration-testing-job:
  stage: integration-test
  rules:
    - if: ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main") && $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    BRANCH_TO_BUILD: "${CI_COMMIT_BRANCH}"
  trigger:
    strategy: "depend"
    project: "advana/gamechanger/gamechanger-test"
    branch: "main"


deploy-job:       # This job runs the build for dev.
  stage: deploy
  rules:
      - if: ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main")
  variables:
    BRANCH_TO_BUILD: "${CI_COMMIT_BRANCH}"
    CI_COMMIT_SHA: "${CI_COMMIT_SHA}"
  trigger:
    strategy: "depend"
    project: "advana/gamechanger/gamechanger-web"
    branch: "main"