image: node:14 # "${IRONBANK_NODEJS}"

stages:          # List of stages for jobs, and their order of execution
  - lint
  - unit-test
  - integration-test
  - deploy

before_script:
  - npm set "@dod-advana:registry" "https://npm.pkg.github.com"
  - npm set "//npm.pkg.github.com/:_authToken" "${NPM_AUTH_TOKEN}"

lint-frontend-test-job:  
  stage: lint   
  cache:
    key: 
      files:
        - frontend/package-lock.json
    paths:
    - .npm/
  script:
    - cd frontend && npm ci --cache ../.npm --prefer-offline
    - npx eslint --ext .js src

lint-backend-test-job:   
  stage: lint    
  cache:
    key: 
      files:
        - backend/package-lock.json
    paths:
    - .npm/
  script:
    - cd backend && npm ci --cache ../.npm --prefer-offline
    - npx eslint --ext .js node_app

unit-backend-test-job:  
  stage: unit-test
  cache:
    key: 
      files:
        - backend/package-lock.json
    paths:
    - .npm/
  script:
    - cd backend && npm ci --cache ../.npm --prefer-offline
    - npm run test:gitlab
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

integration-testing-job:
  stage: integration-test
  rules:
    - if: ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main") && $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    BRANCH_TO_BUILD: "${CI_COMMIT_BRANCH}"
  trigger:
    strategy: "depend"
    project: "advana/gamechanger/gamechanger-test"
    branch: "main"


deploy-job:       # This job runs the build for dev.
  stage: deploy
  rules:
      - if: ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main") && $CI_PIPELINE_SOURCE == "merge_request_event"
  variables:
    BRANCH_TO_BUILD: "${CI_COMMIT_BRANCH}"
    CI_COMMIT_SHA: "${CI_COMMIT_SHA}"
  trigger:
    strategy: "depend"
    project: "advana/gamechanger/gamechanger-web"
    branch: "main"