version: '3'
services:
    web-postgres:
        container_name: web-postgres
        build:
            context: ./postgres/
        ports:
            - "5433:5432"
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        networks:
            - app-net
    redis:
        container_name: redis
        image: redis
        ports: 
            - "6379:6379"
        networks:
            - app-net
    gamechanger-web:
        container_name: gamechanger-web
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                MIGRATION_HOST: postgres
        environment:
            - POSTGRES_HOST_GAME_CHANGER=web-postgres
            - POSTGRES_USER_GAME_CHANGER=postgres
            - POSTGRES_PASSWORD_GAME_CHANGER=password
            - POSTGRES_HOST_GC_ORCHESTRATION=web-postgres
            - POSTGRES_USER_GC_ORCHESTRATION=postgres
            - POSTGRES_PASSWORD_GC_ORCHESTRATION=password
        ports:
            - "5860:5860"
            - "8990:8990"
        volumes:
            - ./:/usr/app/
            # - /usr/app/backend/node_modules
        networks:
            - app-net
        depends_on:
            - web-postgres
            - redis

networks:
    app-net:
        name: "${COMPOSE_PROJECT_NAME:-gc-dev}-network"

volumes:
    postgres:
    mysql:
    matomo:
