version: '3'
services:
    postgres:
        container_name: postgres
        build:
            context: ./postgres/
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    redis:
        container_name: redis
        image: redis
        ports: 
           - "6379:6379"
    # elasticsearch:
    #     container_name: elasticsearch
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    #     environment:
    #         - xpack.security.enabled=false
    #         - discovery.type=single-node
    #     ulimits:
    #         memlock:
    #             soft: -1
    #             hard: -1
    #         nofile:
    #             soft: 65536
    #             hard: 65536
    #     cap_add:
    #     - IPC_LOCK
    #     volumes:
    #     - ./elasticsearch:/usr/share/elasticsearch/data
    #     ports:
    #     - 9200:9200
    #     - 9300:9300
    gamechanger-web-node:
        container_name: gamechanger-web-node
        build:
            context: ./backend/
            args:
                MIGRATION_HOST: postgres
        ports:
            # - "5860:5860"
            - "8990:8990"
        volumes:
            - ./backend/:/usr/src/app/
            - /usr/src/app/node_modules
        depends_on:
            - postgres
            - redis
            # - elasticsearch
    gamechanger-web-react:
        container_name: gamechanger-web-react
        build:
            context: ./frontend/
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/:/usr/src/app/
            - /usr/src/app/node_modules
        depends_on:
            - gamechanger-web-node