version: '3'
services:
    postgres:
        container_name: postgres
        build:
            context: ./postgres/
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
    redis:
        container_name: redis
        image: 10.194.9.80:5000/redis
        ports: 
           - "6379:6379"
    gamechanger-web:
        container_name: gamechanger-web
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                MIGRATION_HOST: postgres
        ports:
            - "5860:5860"
            - "8990:8990"
        volumes:
            - ./:/usr/app/
            # - /usr/app/backend/node_modules
        depends_on:
            - postgres
            - redis