FROM node:14
RUN npm install -g nodemon \
    && npm install -g sequelize-cli \
    && npm install -g jest
COPY . /usr/src/app
WORKDIR /usr/src/app/frontend
RUN npm install
RUN npm run build
RUN mv build ../backend/
WORKDIR /usr/src/app/backend
RUN npm install
CMD ./startProd.sh
