version: '3'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - app-net
    matomo:
        image: matomo:4.3
        container_name: matomo
        environment: 
            - MATOMO_DATABASE_HOST=mysql
            - MATOMO_DATABASE_USERNAME=root
            - MATOMO_DATABASE_PASSWORD=password
            - MATOMO_DATABASE_DBNAME=matomo
        depends_on: 
            - mysql
        ports:
            - 80:80
        volumes:
            - matomo:/var/www/html
        networks:
            - app-net

networks:
  app-net:
    name: "${COMPOSE_PROJECT_NAME:-gc-dev}-network"

volumes:
    mysql:
    matomo:
