{{- if (include "chart.isFileConfigDefined" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fileConfigSecretName" . }}
  labels:
    {{- include "chart.labels" . | nindent 8 }}
data:
  {{- range $key, $val := .Values.fileConfig.files }}
  {{- if not (typeOf $val | eq "<nil>") -}}
  {{- printf "%s: %s" $key ($val | toString | b64enc | quote) | nindent 4 }}
  {{- end -}}
  {{- end }}
{{- end }}