let data = [
	{
		test_id: 1,
		gc_version: 'Latest',
		timestamp: new Date(98, 1),
		source_results: [
			{
				source: 'Coast Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 400,
			},
			{
				source: 'Congress',
				number_of_documents_tested: 16,
				number_of_documents_not_found: 0,
				number_of_documents_found: 16,
				average_position: 2,
			},
			{
				source: 'DFARS',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Health Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Security Cooperation Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of Defense',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Air Force',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Army',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Executive Branch',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FAR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FASAB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FMR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Intelligence Community',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Joint Chiefs of Staff',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'National Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'OMB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Security Technical Implementation Guides',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Marine Corps',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Medicine',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Reserve',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Uncategorized',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Army Training and Doctrine Command',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Code',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
		],
		total_average: 30,
	},
	{
		test_id: 2,
		gc_version: 'Latest',
		timestamp: new Date(2022, 1),
		source_results: [
			{
				source: 'Coast Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 401,
			},
			{
				source: 'Congress',
				number_of_documents_tested: 16,
				number_of_documents_not_found: 0,
				number_of_documents_found: 16,
				average_position: 2,
			},
			{
				source: 'DFARS',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Health Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Security Cooperation Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of Defense',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Air Force',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Army',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Executive Branch',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FAR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FASAB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FMR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Intelligence Community',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Joint Chiefs of Staff',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'National Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'OMB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Security Technical Implementation Guides',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Marine Corps',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Medicine',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Reserve',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Uncategorized',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Army Training and Doctrine Command',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Code',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
		],
		total_average: 0.5,
	},
	{
		test_id: 3,
		gc_version: 'Latest',
		timestamp: new Date(2023, 1),
		source_results: [
			{
				source: 'Coast Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 403,
			},
			{
				source: 'Congress',
				number_of_documents_tested: 16,
				number_of_documents_not_found: 0,
				number_of_documents_found: 16,
				average_position: 2,
			},
			{
				source: 'DFARS',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Health Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Defense Security Cooperation Agency',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of Defense',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Air Force',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Dept. of the Army',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Executive Branch',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FAR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FASAB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'FMR',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Intelligence Community',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Joint Chiefs of Staff',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'National Guard',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'OMB',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Security Technical Implementation Guides',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Marine Corps',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Medicine',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'US Navy Reserve',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'Uncategorized',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Army Training and Doctrine Command',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
			{
				source: 'United States Code',
				number_of_documents_tested: 3,
				number_of_documents_not_found: 0,
				number_of_documents_found: 3,
				average_position: 1,
			},
		],
		total_average: 0.5,
	},
];

export default data;
