{{- if .Values.service -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- toYaml (list .Values.service.http .Values.service.https) | nindent 4 }}
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
