const tutorialObject = {
	backButtonID: undefined,
	buttonID: undefined,
	clickBack: undefined,
	clickButton: undefined,
	content: undefined,
	disableBeacon: true,
	disableScrolling: undefined,
	input: undefined,
	inputID: undefined,
	inputText: undefined,
	placement: 'auto',
	target: undefined,
	testA: undefined,
	testB: undefined,
	title: undefined,
};

const reTutorialSteps = [
	{
		...tutorialObject,
		target: '.re-tutorial-step-1',
		type: 'display',
		title: 'This is a test',
		placement: 'auto',
		content: "These are filters. They do what filters do. It's pretty neat and stuff",
		step_number: 1,
		component_name: 'Test Component',
	},
	// {
	// 	type: 'display',
	// 	title: 'SEARCH',
	// 	step_text: 'Search across our comprehensive policy corpus with simple or complex queries.',
	// 	step_number: 2,
	// 	component_name: 'Search Bar',
	// },
	// {
	// 	type: 'input',
	// 	input: true,
	// 	title: 'STRUCTURE',
	// 	input_ID: 'gcSearchInput',
	// 	button_ID: 'gcSearchButton',
	// 	step_text:
	// 		'Build your queries with quotes to define exact phrases, plain keywords, or combine terms with boolean operators (AND, OR). For example "artificial intelligence" and president.',
	// 	input_text: '"artificial intelligence" and president',
	// 	step_number: 3,
	// 	click_button: true,
	// 	component_name: 'Search Input',
	// },
	// {
	// 	type: 'display',
	// 	title: 'Results',
	// 	parent: 'Search Results Section',
	// 	placement: 'right',
	// 	step_text:
	// 		'Our default Grid View displays results in categories. Matched terms are highlighted in each snippet in interactive cards. Click "Open" to access the full PDF, "Details" to find more information about referenced policies, or "More" to view metadata extracted from each result.',
	// 	step_number: 4,
	// 	component_name: 'Search Result Card',
	// 	disableScrolling: true,
	// },
	// {
	// 	type: 'display',
	// 	title: 'Filters',
	// 	button_ID: 'gcAdvancedSettings',
	// 	step_text: 'Tailor queries with advanced filters.',
	// 	step_number: 5,
	// 	click_button: false,
	// 	component_name: 'Advanced Settings',
	// },
	// {
	// 	type: 'display',
	// 	title: 'View Dropdown',
	// 	step_text: 'Explore other views for different ways to analyze results.',
	// 	step_number: 6,
	// 	component_name: 'Change View',
	// },
	// {
	// 	type: 'button',
	// 	title: 'Share Your Search',
	// 	button_ID: 'gcShareSearch',
	// 	step_text: 'Easily send tailored search results to colleagues by clicking here for a shareable link.',
	// 	step_number: 7,
	// 	click_button: false,
	// 	component_name: 'Share Search',
	// },
	// {
	// 	type: 'button',
	// 	title: 'Export',
	// 	button_ID: 'gcOpenSelectedDocsDrawer',
	// 	step_text: 'Export all or selected results in csv, json, or pdf formats.',
	// 	step_number: 8,
	// 	click_button: false,
	// 	component_name: 'Open Selected Documents Drawer',
	// },
	// {
	// 	type: 'display',
	// 	title: 'Slide-out Menu',
	// 	placement: 'right',
	// 	step_text: 'Check out our menu for additional features, capabilities, and support.',
	// 	step_number: 9,
	// 	component_name: 'Slide-out Menu',
	// },
	// {
	// 	type: 'button',
	// 	title: 'More Help',
	// 	button_ID: 'gcUserGuide',
	// 	step_text: 'Want more help? Explore our User Guide here for more information on each of our features.',
	// 	step_number: 10,
	// 	click_button: false,
	// 	component_name: 'User Guide',
	// },
];

export { reTutorialSteps };
