name: Anchore Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build --file DockerfileTest --build-arg NPMRC_FILE="${{secrets.NPMRC_FILE}}" --tag gamechanger/gamechanger-web:latest .
    - uses: anchore/scan-action@v1
      with:
        image-reference: "gamechanger/gamechanger-web:latest
        dockerfile-path: "./DockerfileTest"
        fail-build: true
     # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
