name: Lint

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ dev, main ]

jobs:
  eslint-Frontend:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd frontend
    - run: cp frontend/package-lock.json package-lock.json
    - name: Use Node.js '18'
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        registry-url: https://npm.pkg.github.com
        scope: '@dod-advana'
    - run: |
            cd frontend && npm install && npx eslint --ext .js src
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPMRC_FILE}}

  eslint-Backend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: cd backend
      - run: cp backend/package-lock.json package-lock.json
      - name: Use Node.js '18'
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: https://npm.pkg.github.com
          scope: '@dod-advana'
      - run: |
          cd backend && npm install && npx eslint --ext .js node_app
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMRC_FILE}}


