
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (only needed for slack_mention_mapping_file)
        uses: actions/checkout@v2
      - name: Slack notification
        uses: tiloio/slack-webhook-action@v1.1.2
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_json: '{
            "username": "{{GITHUB_ACTOR}}",
            "text": "{{GITHUB_ACTOR}} made a pull request",
            "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
            "channel": "#gamechanger-notifications",
            "blocks": [
            {
            "type": "section",
            "text": {
            "type": "mrkdwn",
            "text": "{{GITHUB_ACTOR}} made a pull request.\n_{{CUSTOM_COMMIT_MSG}}_"
            }
            },
            {
            "type": "context",
            "elements": [
            {
            "type": "mrkdwn",
            "text": ":speech_balloon: commit <{{CUSTOM_COMMIT_URL}}|{{CUSTOM_SHORT_GITHUB_SHA}}>"
            }
            ]
            }
            ]
            }'
