
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  pull_request:
    branches: ["dev", "main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: kceb/pull-request-url-action@v1
        id: pr-url
      - name: Slack notification
        uses: tiloio/slack-webhook-action@v1.1.2
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_json: '{
            "username": "{{GITHUB_ACTOR}}",
            "text": "{{GITHUB_ACTOR}} made a pull request",
            "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
            "channel": "#gamechanger-notifications",
            "blocks": [
                {
                  "accessory": {
                    "type": "image",
                    "image_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                    "alt_text": "GitHub Icon"
                  },
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "{{GITHUB_ACTOR}} Made a GitHub Pull Request.\n_{{CUSTOM_COMMIT_MSG}}_ "
                  }
                },
                {
                   "type": "context",
                   "elements": [
                       {
                           "type": "mrkdwn",
                           "text": ":git-pull-request: PR <https://github.com/${repositoryName}/commit/${commitSHA}|Pull Request Link>"
                       }
                   ]
               }
              ]
            }'
