# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - dev
      - 'feature/**'
      - 'hotfix/**'
      - 'bugfix/sprint-**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd backend
    - run: cp backend/package-lock.json package-lock.json
    - name: Use Node.js '14'
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://npm.pkg.github.com
        scope: '@dod-advana'
    - run: |
            cd backend && npm install jest && npm install && npm run test
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPMRC_FILE}}
